language: ruby
rvm:
  - 1.9.3
  - 2.1.5
  - 2.2.0
  - 2.2.1

cache: bundler

addons:
  apt:
    packages:
      - rdnssd
      - libavahi-compat-libdnssd-dev
      - youtube-dl

before_script:
  - which youtube-dl
  - youtube-dl --version

script: bundle exec rake spec
